BLOODLINK_DB_URL=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
BLOODLINK_DB_USER=postgres.fgqrfdjoambaecwducpf
BLOODLINK_DB_PASSWORD=yLtVQD9QIlC7ee13
BLOODLINK_IA_PROVIDER=openrouter
BLOODLINK_AUDIT_IA_PROVIDER=openrouter
BLOODLINK_DONATION_IA_PROVIDER=anthropic
BLOODLINK_OPENROUTER_API_KEY=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
BLOODLINK_ANTHROPIC_API_KEY=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
BLOODLINK_ANTHROPIC_MODEL=claude-sonnet-4-20250514
BLOODLINK_OPENROUTER_MODEL=openrouter/free
